CREATE DATABASE IF NOT EXISTS PROJETO_ONG;

DROP TABLE MENSAGEM;
DROP TABLE CHAT;
DROP TABLE FEEDBACKS;
DROP TABLE PALAVRAS_CHAVE;
DROP TABLE INTERESSES;
DROP TABLE ONGS;
DROP TABLE VOLUNTARIOS;
DROP TABLE CONTA;

USE PROJETO_ONG;
SELECT * FROM CONTA;
delete from PROJETO_ONG.CONTA where EMAIL = 'fernando.affonso@connectparts.com.br';
delete from PROJETO_ONG.CONTA where EMAIL = 'thomedeiros@hotmail.com';
SELECT EMAIL, VERIFICADA FROM CONTA;
ALTER TABLE PROJETO_ONG.CONTA ADD DATA_ATUALIZACAO DATETIME NOT NULL DEFAULT NOW();

SELECT COUNT(EMAIL) FROM CONTA WHERE EMAIL = 'thomaz@turbante.com.br';

INSERT INTO PROJETO_ONG.CONTA (EMAIL, SENHA, TIPO_CONTA, DATA_CRIACAO, HASH, VERIFICADA)
VALUES ('thomaz@turbante.com.br', '28s86d291378sds9', 'Voluntario', '2021-10-30 00:23:00', '219s8da9092890s', 0);

TRUNCATE TABLE PROJETO_ONG.CONTA;
